import type { SportTag } from './sports';

/**
 * Curated publisher catalog — single place to add or edit outlets.
 * Used by the API (RSS ingest) and the app (Sources screen + offline fallback).
 *
 * primaryTopic: main "curiosity" for grouping in Profile → Sources (more UX coming).
 * topics: candidate article tags for keyword inference in normalize (primaryTopic is fallback).
 * sportTags: default sport/league facets for articles from this feed.
 */
export type Topic =
  | 'technology'
  | 'culture'
  | 'science'
  | 'business'
  | 'politics'
  | 'health'
  | 'design'
  | 'world'
  | 'sports'
  | 'art'
  | 'gardening'
  | 'gaming';

export interface SourceCatalogEntry {
  id: string;
  url: string;
  name: string;
  description: string;
  primaryTopic: Topic;
  topics: Topic[];
  /** Default sport/league tags applied at ingest for sports feeds. */
  sportTags?: SportTag[];
  /** Explicit logo URL; omit to auto-derive from feed URL via favicon CDN. */
  logoUrl?: string;
  /** Brand domain when feed hostname differs (e.g. feeds.bbci.co.uk → bbc.co.uk). */
  logoDomain?: string;
  /**
   * Publisher often uses per-article paywalls. Never marks every article alone;
   * combined with RSS signals and short/teaser body heuristics at ingest.
   */
  subscriptionPublisher?: boolean;
  /** Per-feed fetch timeout (ms). Default 15000 in ingest when omitted. */
  fetchTimeoutMs?: number;
}

export const SOURCE_CATALOG: SourceCatalogEntry[] = [
  // —— World & breaking news ——
  {
    id: 'bbc-news',
    url: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    name: 'BBC News',
    description: 'Global news and current events',
    primaryTopic: 'world',
    topics: ['world', 'politics'],
    logoDomain: 'bbc.co.uk',
  },
  {
    id: 'cnn',
    url: 'http://rss.cnn.com/rss/cnn_topstories.rss',
    name: 'CNN',
    description: 'Breaking news and top stories',
    primaryTopic: 'world',
    topics: ['world', 'politics'],
  },
  {
    id: 'fox-news',
    url: 'https://moxie.foxnews.com/google-publisher/latest.xml',
    name: 'Fox News',
    description: 'U.S. and world headlines',
    primaryTopic: 'world',
    topics: ['world', 'politics'],
  },
  {
    id: 'npr',
    url: 'https://feeds.npr.org/1001/rss.xml',
    name: 'NPR',
    description: 'National and international news',
    primaryTopic: 'world',
    topics: ['world', 'culture', 'politics'],
  },
  {
    id: 'guardian',
    url: 'https://www.theguardian.com/world/rss',
    name: 'The Guardian',
    description: 'World news and analysis',
    primaryTopic: 'world',
    topics: ['world', 'politics'],
  },
  {
    id: 'al-jazeera',
    url: 'https://www.aljazeera.com/xml/rss/all.xml',
    name: 'Al Jazeera',
    description: 'International news and perspectives',
    primaryTopic: 'world',
    topics: ['world', 'politics'],
  },
  {
    id: 'rest-of-world',
    url: 'https://restofworld.org/feed/latest',
    name: 'Rest of World',
    description: 'Technology and society outside the West',
    primaryTopic: 'world',
    topics: ['world', 'technology', 'culture'],
  },
  {
    id: 'pbs-newshour',
    url: 'https://www.pbs.org/newshour/feeds/rss/headlines',
    name: 'PBS NewsHour',
    description: 'In-depth U.S. and global reporting',
    primaryTopic: 'world',
    topics: ['world', 'politics'],
  },

  // —— Politics & policy ——
  {
    id: 'nyt',
    url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
    name: 'The New York Times',
    description: 'National and international coverage',
    primaryTopic: 'politics',
    topics: ['politics', 'world', 'culture'],
    subscriptionPublisher: true,
  },
  {
    id: 'washington-post',
    url: 'https://feeds.washingtonpost.com/rss/world',
    name: 'The Washington Post',
    description: 'Politics and world affairs',
    primaryTopic: 'politics',
    topics: ['politics', 'world'],
    subscriptionPublisher: true,
  },
  {
    id: 'msnbc',
    url: 'https://www.ms.now/rss',
    name: 'MSNBC',
    description: 'U.S. politics and news',
    primaryTopic: 'politics',
    topics: ['politics', 'world'],
    logoDomain: 'msnbc.com',
  },
  {
    id: 'vox',
    url: 'https://www.vox.com/rss/index.xml',
    name: 'Vox',
    description: 'Policy, politics, and explainers',
    primaryTopic: 'politics',
    topics: ['politics', 'culture'],
  },
  {
    id: 'axios',
    url: 'https://www.axios.com/feeds/feed.rss',
    name: 'Axios',
    description: 'Politics, business, and tech briefs',
    primaryTopic: 'politics',
    topics: ['politics', 'business', 'technology'],
  },
  {
    id: 'huffpost',
    url: 'https://www.huffpost.com/section/front-page/feed',
    name: 'HuffPost',
    description: 'News and opinion',
    primaryTopic: 'politics',
    topics: ['politics', 'culture'],
  },
  {
    id: 'propublica',
    url: 'https://www.propublica.org/feeds/propublica/main',
    name: 'ProPublica',
    description: 'Investigative journalism',
    primaryTopic: 'politics',
    topics: ['politics', 'world'],
  },
  {
    id: 'the-atlantic',
    url: 'https://feeds.feedburner.com/TheAtlantic',
    name: 'The Atlantic',
    description: 'Culture, politics, and long-form journalism',
    primaryTopic: 'politics',
    topics: ['culture', 'politics', 'world'],
    logoDomain: 'theatlantic.com',
    subscriptionPublisher: true,
  },

  // —— Technology ——
  {
    id: 'techcrunch',
    url: 'https://techcrunch.com/feed/',
    name: 'TechCrunch',
    description: 'Startups, venture, and tech industry',
    primaryTopic: 'technology',
    topics: ['technology', 'business'],
  },
  {
    id: 'ars-technica',
    url: 'https://feeds.arstechnica.com/arstechnica/index',
    name: 'Ars Technica',
    description: 'Technology, science, and policy',
    primaryTopic: 'technology',
    topics: ['technology', 'science'],
  },
  {
    id: 'mit-tech-review',
    url: 'https://www.technologyreview.com/feed/',
    name: 'MIT Technology Review',
    description: 'Emerging technology and research',
    primaryTopic: 'technology',
    topics: ['technology', 'science'],
  },
  {
    id: 'wired',
    url: 'https://www.wired.com/feed/rss',
    name: 'Wired',
    description: 'Tech, science, and digital culture',
    primaryTopic: 'technology',
    topics: ['technology', 'culture'],
  },
  {
    id: 'the-verge',
    url: 'https://www.theverge.com/rss/index.xml',
    name: 'The Verge',
    description: 'Consumer tech and gadgets',
    primaryTopic: 'technology',
    topics: ['technology', 'culture'],
  },
  {
    id: 'engadget',
    url: 'https://www.engadget.com/rss.xml',
    name: 'Engadget',
    description: 'Gadgets and consumer electronics',
    primaryTopic: 'technology',
    topics: ['technology'],
  },
  {
    id: 'cnet',
    url: 'https://www.cnet.com/rss/news/',
    name: 'CNET',
    description: 'Tech news, reviews, and how-tos',
    primaryTopic: 'technology',
    topics: ['technology'],
  },
  {
    id: 'gizmodo',
    url: 'https://gizmodo.com/rss',
    name: 'Gizmodo',
    description: 'Tech, science, and internet culture',
    primaryTopic: 'technology',
    topics: ['technology', 'science', 'culture'],
  },
  {
    id: 'mashable',
    url: 'https://mashable.com/feeds/rss/all',
    name: 'Mashable',
    description: 'Digital culture and entertainment tech',
    primaryTopic: 'technology',
    topics: ['technology', 'culture'],
  },

  // —— Business & markets ——
  {
    id: 'bloomberg',
    url: 'https://feeds.bloomberg.com/markets/news.rss',
    name: 'Bloomberg',
    description: 'Markets, business, and finance',
    primaryTopic: 'business',
    topics: ['business', 'world'],
    subscriptionPublisher: true,
  },
  {
    id: 'economist',
    url: 'https://www.economist.com/the-world-this-week/rss.xml',
    name: 'The Economist',
    description: 'Global business and affairs',
    primaryTopic: 'business',
    topics: ['business', 'world', 'politics'],
    subscriptionPublisher: true,
  },
  {
    id: 'forbes',
    url: 'https://www.forbes.com/innovation/feed2/',
    name: 'Forbes',
    description: 'Business, innovation, and leadership',
    primaryTopic: 'business',
    topics: ['business', 'technology'],
  },

  // —— Science & health ——
  {
    id: 'scientific-american',
    url: 'https://www.scientificamerican.com/platform/syndication/rss/',
    name: 'Scientific American',
    description: 'Science news and research',
    primaryTopic: 'science',
    topics: ['science', 'health'],
  },

  // —— Culture & ideas ——
  {
    id: 'new-yorker',
    subscriptionPublisher: true,
    url: 'https://www.newyorker.com/feed/everything',
    name: 'The New Yorker',
    description: 'Reporting, fiction, and criticism',
    primaryTopic: 'culture',
    topics: ['culture', 'politics'],
    logoDomain: 'newyorker.com',
  },
  {
    id: 'slate',
    url: 'https://www.slate.com/feeds/all.rss',
    name: 'Slate',
    description: 'News, politics, and culture',
    primaryTopic: 'culture',
    topics: ['culture', 'politics'],
  },

  // —— Apparel & style ——
  {
    id: 'gq',
    url: 'https://www.gq.com/feed/rss',
    name: 'GQ',
    description: 'Menswear, style, culture, and grooming',
    primaryTopic: 'culture',
    topics: ['culture', 'design'],
    logoDomain: 'gq.com',
  },
  {
    id: 'esquire',
    url: 'https://www.esquire.com/rss/all.xml/',
    name: 'Esquire',
    description: 'Style, culture, and lifestyle for men',
    primaryTopic: 'culture',
    topics: ['culture', 'design'],
    logoDomain: 'esquire.com',
  },
  {
    id: 'vogue',
    url: 'https://www.vogue.com/feed/rss',
    name: 'Vogue',
    description: 'Fashion, beauty, and runway coverage',
    primaryTopic: 'culture',
    topics: ['culture', 'design'],
    subscriptionPublisher: true,
    logoDomain: 'vogue.com',
  },
  {
    id: 'harpers-bazaar',
    url: 'https://www.harpersbazaar.com/rss/all.xml/',
    name: "Harper's Bazaar",
    description: 'Fashion, beauty, and luxury style',
    primaryTopic: 'culture',
    topics: ['culture', 'design'],
    logoDomain: 'harpersbazaar.com',
  },
  {
    id: 'highsnobiety',
    url: 'https://www.highsnobiety.com/feed/',
    name: 'Highsnobiety',
    description: 'Streetwear, sneakers, and fashion culture',
    primaryTopic: 'culture',
    topics: ['culture', 'design'],
    logoDomain: 'highsnobiety.com',
  },
  {
    id: 'hypebeast',
    url: 'https://hypebeast.com/feed',
    name: 'HYPEBEAST',
    description: 'Streetwear, sneakers, and apparel drops',
    primaryTopic: 'culture',
    topics: ['culture', 'design'],
    logoDomain: 'hypebeast.com',
  },
  {
    id: 'fashionista',
    url: 'https://www.fashionista.com/.rss/excerpt',
    name: 'Fashionista',
    description: 'Fashion industry news and trends',
    primaryTopic: 'culture',
    topics: ['culture', 'design'],
    logoDomain: 'fashionista.com',
  },
  {
    id: 'wwd',
    url: 'https://wwd.com/feed/',
    name: 'WWD',
    description: 'Fashion business, retail, and apparel industry',
    primaryTopic: 'culture',
    topics: ['culture', 'business', 'design'],
    subscriptionPublisher: true,
    logoDomain: 'wwd.com',
  },
  {
    id: 'business-of-fashion',
    url: 'https://www.businessoffashion.com/feed/',
    name: 'The Business of Fashion',
    description: 'Fashion industry analysis and luxury apparel',
    primaryTopic: 'culture',
    topics: ['culture', 'business', 'design'],
    subscriptionPublisher: true,
    logoDomain: 'businessoffashion.com',
  },
  {
    id: 'cool-hunting',
    url: 'https://www.coolhunting.com/feed/',
    name: 'Cool Hunting',
    description: 'Design, style, travel, and product culture',
    primaryTopic: 'culture',
    topics: ['culture', 'design'],
    logoDomain: 'coolhunting.com',
  },

  // —— Sports ——
  {
    id: 'espn',
    url: 'https://www.espn.com/espn/rss/news',
    name: 'ESPN',
    description: 'Sports news and scores',
    primaryTopic: 'sports',
    topics: ['sports'],
  },
  {
    id: 'espn-nfl',
    url: 'https://www.espn.com/espn/rss/nfl/news',
    name: 'ESPN NFL',
    description: 'NFL news, scores, and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['football'],
    logoDomain: 'espn.com',
  },
  {
    id: 'espn-nba',
    url: 'https://www.espn.com/espn/rss/nba/news',
    name: 'ESPN NBA',
    description: 'NBA news, scores, and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['basketball'],
    logoDomain: 'espn.com',
  },
  {
    id: 'espn-mlb',
    url: 'https://www.espn.com/espn/rss/mlb/news',
    name: 'ESPN MLB',
    description: 'MLB news, scores, and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['baseball'],
    logoDomain: 'espn.com',
  },
  {
    id: 'espn-nhl',
    url: 'https://www.espn.com/espn/rss/nhl/news',
    name: 'ESPN NHL',
    description: 'NHL news, scores, and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['hockey'],
    logoDomain: 'espn.com',
  },
  {
    id: 'espn-soccer',
    url: 'https://www.espn.com/espn/rss/soccer/news',
    name: 'ESPN Soccer',
    description: 'Soccer and international football',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer'],
    logoDomain: 'espn.com',
  },
  {
    id: 'espn-college-football',
    url: 'https://www.espn.com/espn/rss/college-football/news',
    name: 'ESPN College Football',
    description: 'NCAA football news and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['college-football'],
    logoDomain: 'espn.com',
  },
  {
    id: 'cbs-sports',
    url: 'https://www.cbssports.com/rss/headlines/',
    name: 'CBS Sports',
    description: 'Major league and college sports headlines',
    primaryTopic: 'sports',
    topics: ['sports'],
  },
  {
    id: 'yahoo-sports',
    url: 'https://sports.yahoo.com/rss/',
    name: 'Yahoo Sports',
    description: 'Sports news across major leagues',
    primaryTopic: 'sports',
    topics: ['sports'],
  },
  {
    id: 'mlb-com',
    url: 'https://www.mlb.com/feeds/news/rss.xml',
    name: 'MLB.com',
    description: 'Official Major League Baseball news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['baseball'],
    logoDomain: 'mlb.com',
  },
  {
    id: 'bbc-sport',
    url: 'https://feeds.bbci.co.uk/sport/rss.xml',
    name: 'BBC Sport',
    description: 'Global sports coverage',
    primaryTopic: 'sports',
    topics: ['sports'],
    logoDomain: 'bbc.co.uk',
  },
  {
    id: 'bbc-sport-football',
    url: 'https://feeds.bbci.co.uk/sport/football/rss.xml',
    name: 'BBC Sport Football',
    description: 'Football and international soccer',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer'],
    logoDomain: 'bbc.co.uk',
  },
  {
    id: 'sky-sports-pl',
    url: 'https://www.skysports.com/rss/11661',
    name: 'Sky Sports Premier League',
    description: 'Premier League news, transfers, and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'premier-league'],
    logoDomain: 'skysports.com',
  },
  {
    id: 'guardian-sport',
    url: 'https://www.theguardian.com/sport/rss',
    name: 'The Guardian Sport',
    description: 'Sports news and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'guardian-football',
    url: 'https://www.theguardian.com/football/rss',
    name: 'The Guardian Football',
    description: 'Football and international soccer',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'bbc-premier-league',
    url: 'https://feeds.bbci.co.uk/sport/football/premier-league/rss.xml',
    name: 'BBC Sport Premier League',
    description: 'Premier League news and match coverage',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'premier-league'],
    logoDomain: 'bbc.co.uk',
  },
  {
    id: 'guardian-premier-league',
    url: 'https://www.theguardian.com/football/premierleague/rss',
    name: 'The Guardian Premier League',
    description: 'Premier League news, analysis, and features',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'premier-league'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'espn-uk-football',
    url: 'https://www.espn.co.uk/espn/rss/football/news',
    name: 'ESPN UK Football',
    description: 'UK and European football news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer'],
    logoDomain: 'espn.co.uk',
  },
  {
    id: 'bbc-european-football',
    url: 'https://feeds.bbci.co.uk/sport/football/european/rss.xml',
    name: 'BBC Sport European Football',
    description: 'European club and international football',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer'],
    logoDomain: 'bbc.co.uk',
  },
  {
    id: 'bbc-champions-league',
    url: 'https://feeds.bbci.co.uk/sport/football/champions-league/rss.xml',
    name: 'BBC Sport Champions League',
    description: 'UEFA Champions League news and match reports',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'champions-league'],
    logoDomain: 'bbc.co.uk',
  },
  {
    id: 'guardian-champions-league',
    url: 'https://www.theguardian.com/football/championsleague/rss',
    name: 'The Guardian Champions League',
    description: 'Champions League news and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'champions-league'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'marca',
    url: 'https://www.marca.com/rss/futbol.xml',
    name: 'Marca',
    description: 'Spanish and La Liga football news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'la-liga'],
    logoDomain: 'marca.com',
  },
  {
    id: 'football-italia',
    url: 'https://www.football-italia.net/feed',
    name: 'Football Italia',
    description: 'Serie A and Italian football news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'serie-a'],
    logoDomain: 'football-italia.net',
  },
  {
    id: 'bundesliga',
    url: 'https://www.bundesliga.com/en/bundesliga/news/rss',
    name: 'Bundesliga',
    description: 'Official Bundesliga news and features',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'bundesliga'],
    logoDomain: 'bundesliga.com',
  },
  {
    id: 'guardian-bundesliga',
    url: 'https://www.theguardian.com/football/bundesligafootball/rss',
    name: 'The Guardian Bundesliga',
    description: 'Bundesliga news and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer', 'bundesliga'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'fourfourtwo',
    url: 'https://www.fourfourtwo.com/feeds/all',
    name: 'FourFourTwo',
    description: 'European and world football news and features',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['soccer'],
    logoDomain: 'fourfourtwo.com',
  },
  {
    id: 'guardian-baseball',
    url: 'https://www.theguardian.com/sport/baseball/rss',
    name: 'The Guardian Baseball',
    description: 'Major League Baseball news and analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['baseball'],
    logoDomain: 'theguardian.com',
  },

  // —— Outdoor adventure & cycling ——
  {
    id: 'outside-tv',
    url: 'https://www.outsideonline.com/rss/all/rss.xml',
    name: 'Outside TV',
    description: 'Outdoor adventure, gear, and sports from the Outside network',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'outsideonline.com',
  },
  {
    id: 'velo',
    url: 'https://velo.outsideonline.com/feed',
    name: 'Velo',
    description: 'Road, gravel, and pro cycling news and race coverage',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'outsideonline.com',
  },
  {
    id: 'bikeradar',
    url: 'https://feeds.purplemanager.com/193c804a-a673-47bd-b09b-11baf4822a17/bikeradar-news',
    name: 'BikeRadar',
    description: 'Bike news, reviews, and buying advice',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'bikeradar.com',
  },
  {
    id: 'bikeradar-road',
    url: 'https://feeds.purplemanager.com/193c804a-a673-47bd-b09b-11baf4822a17/bikeradar-road-news',
    name: 'BikeRadar Road',
    description: 'Road cycling news, reviews, and features',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'bikeradar.com',
  },
  {
    id: 'bikeradar-mtb',
    url: 'https://feeds.purplemanager.com/193c804a-a673-47bd-b09b-11baf4822a17/bikeradar-mtb-feed',
    name: 'BikeRadar MTB',
    description: 'Mountain biking news, reviews, and features',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['mtb'],
    logoDomain: 'bikeradar.com',
  },
  {
    id: 'road-cc',
    url: 'https://road.cc/rss',
    name: 'road.cc',
    description: 'Road cycling news, reviews, and commuting',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'road.cc',
  },
  {
    id: 'cyclingnews',
    url: 'https://www.cyclingnews.com/feeds/news/',
    name: 'Cyclingnews',
    description: 'Pro racing, transfers, and cycling news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'cyclingnews.com',
  },
  {
    id: 'cycling-weekly',
    url: 'https://www.cyclingweekly.com/feeds/tag/news',
    name: 'Cycling Weekly',
    description: 'UK and international cycling news and reviews',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'cyclingweekly.com',
  },
  {
    id: 'singletracks',
    url: 'https://www.singletracks.com/feed/',
    name: 'Singletracks',
    description: 'Mountain bike news, trails, and gear',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['mtb'],
    logoDomain: 'singletracks.com',
  },
  {
    id: 'flow-mountain-bike',
    url: 'https://www.flowmountainbike.com/feed/',
    name: 'Flow Mountain Bike',
    description: 'MTB culture, reviews, and riding stories',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['mtb'],
    logoDomain: 'flowmountainbike.com',
  },
  {
    id: 'enduro-mtb',
    url: 'https://enduro-mtb.com/en/feed/',
    name: 'Enduro MTB',
    description: 'Enduro and trail mountain biking news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['mtb'],
    logoDomain: 'enduro-mtb.com',
  },
  {
    id: 'mbr',
    url: 'https://www.mbr.co.uk/feed',
    name: 'MBR',
    description: 'UK mountain biking news, tests, and skills',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['mtb'],
    logoDomain: 'mbr.co.uk',
  },
  {
    id: 'bikemag',
    url: 'https://www.bikemag.com/feed/',
    name: 'Bike Magazine',
    description: 'Mountain bike reviews, features, and industry news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['mtb'],
    logoDomain: 'bikemag.com',
  },
  {
    id: 'bicycling',
    url: 'https://www.bicycling.com/rss/all.xml/',
    name: 'Bicycling',
    description: 'Road, gravel, and general cycling news and training',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'bicycling.com',
  },
  {
    id: 'gravel-cyclist',
    url: 'https://www.gravelcyclist.com/feed/',
    name: 'Gravel Cyclist',
    description: 'Gravel riding news, bikes, and adventure routes',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'gravelcyclist.com',
  },
  {
    id: 'gran-fondo-cycling',
    url: 'https://granfondo-cycling.com/feed/',
    name: 'Gran Fondo Cycling',
    description: 'Road cycling, gran fondos, and sportive coverage',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'granfondo-cycling.com',
  },
  {
    id: 'velonews',
    url: 'https://www.velonews.com/feed/',
    name: 'VeloNews',
    description: 'Pro road racing, training, and cycling analysis',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'velonews.com',
  },
  {
    id: 'bikepacking',
    url: 'https://www.bikepacking.com/feed/',
    name: 'Bikepacking.com',
    description: 'Bikepacking routes, gear, and adventure cycling',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'bikepacking.com',
  },
  {
    id: 'pinkbike',
    url: 'https://feeds.feedburner.com/Pinkbike',
    name: 'Pinkbike',
    description: 'Mountain bike news, reviews, and community',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['mtb'],
    logoDomain: 'pinkbike.com',
  },
  {
    id: 'decline',
    url: 'https://www.decline.com/feed/',
    name: 'Decline',
    description: 'Mountain biking, snowboarding, and action sports culture',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    sportTags: ['mtb'],
    logoDomain: 'decline.com',
  },
  {
    id: 'cyclist-mag',
    url: 'https://www.cyclist.co.uk/feed/',
    name: 'Cyclist',
    description: 'Road cycling magazine — bikes, rides, and pro racing',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'cyclist.co.uk',
  },
  {
    id: 'pez-cycling',
    url: 'https://www.pezcyclingnews.com/feed/',
    name: 'PezCycling News',
    description: 'Pro peloton news, tech, and race coverage',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'pezcyclingnews.com',
  },
  {
    id: 'dcrainmaker',
    url: 'https://www.dcrainmaker.com/feed',
    name: 'DC Rainmaker',
    description: 'Cycling, running, and endurance sports tech reviews',
    primaryTopic: 'sports',
    topics: ['sports', 'technology'],
    sportTags: ['cycling', 'running'],
    logoDomain: 'dcrainmaker.com',
  },
  {
    id: 'guardian-cycling',
    url: 'https://www.theguardian.com/sport/cycling/rss',
    name: 'The Guardian Cycling',
    description: 'Cycling news, racing, and opinion',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['cycling'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'runners-world',
    url: 'https://www.runnersworld.com/rss/all.xml/',
    name: "Runner's World",
    description: 'Running training, gear, and race news',
    primaryTopic: 'sports',
    topics: ['sports', 'health'],
    sportTags: ['running'],
    logoDomain: 'runnersworld.com',
  },
  {
    id: 'runners-world-uk',
    url: 'https://www.runnersworld.com/uk/rss/all.xml/',
    name: "Runner's World UK",
    description: 'UK running news, training, and gear',
    primaryTopic: 'sports',
    topics: ['sports', 'health'],
    sportTags: ['running'],
    logoDomain: 'runnersworld.com',
  },
  {
    id: 'trail-runner',
    url: 'https://www.trailrunnermag.com/feed/',
    name: 'Trail Runner',
    description: 'Trail and ultrarunning news and features',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['running'],
    logoDomain: 'trailrunnermag.com',
  },
  {
    id: 'womens-running',
    url: 'https://www.womensrunning.com/feed/',
    name: "Women's Running",
    description: 'Running news and training for women',
    primaryTopic: 'sports',
    topics: ['sports', 'health'],
    sportTags: ['running'],
    logoDomain: 'womensrunning.com',
  },
  {
    id: 'outside-run',
    url: 'https://run.outsideonline.com/feed',
    name: 'Outside Run',
    description: 'Running stories from the Outside network',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['running'],
    logoDomain: 'outsideonline.com',
  },
  {
    id: 'irunfar',
    url: 'https://www.irunfar.com/feed',
    name: 'iRunFar',
    description: 'Ultrarunning, trail races, and mountain running',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['running'],
    logoDomain: 'irunfar.com',
  },
  {
    id: 'letsrun',
    url: 'https://www.letsrun.com/feed/',
    name: 'LetsRun',
    description: 'Track, cross country, and distance running news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['running', 'xc'],
    logoDomain: 'letsrun.com',
  },
  {
    id: 'guardian-running',
    url: 'https://www.theguardian.com/lifeandstyle/running/rss',
    name: 'The Guardian Running',
    description: 'Running news, training, and lifestyle',
    primaryTopic: 'sports',
    topics: ['sports', 'health'],
    sportTags: ['running'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'faster-skier',
    url: 'https://fasterskier.com/feed/',
    name: 'FasterSkier',
    description: 'Cross-country skiing and nordic racing news',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['xc'],
    logoDomain: 'fasterskier.com',
  },
  {
    id: 'ski-racing',
    url: 'https://www.skiracing.com/feed/',
    name: 'Ski Racing',
    description: 'Alpine and cross-country ski racing coverage',
    primaryTopic: 'sports',
    topics: ['sports'],
    sportTags: ['xc'],
    logoDomain: 'skiracing.com',
  },
  {
    id: 'backpacker',
    url: 'https://www.backpacker.com/feed/',
    name: 'Backpacker',
    description: 'Hiking, backpacking, and trail gear',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'backpacker.com',
  },
  {
    id: 'climbing',
    url: 'https://www.climbing.com/feed/',
    name: 'Climbing',
    description: 'Rock climbing, bouldering, and mountaineering',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'climbing.com',
  },
  {
    id: 'alpinist',
    url: 'https://www.alpinist.com/rss/',
    name: 'Alpinist',
    description: 'Alpine climbing and mountaineering stories',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'alpinist.com',
  },
  {
    id: 'powder',
    url: 'https://www.powder.com/feed/',
    name: 'Powder',
    description: 'Skiing culture, resorts, and backcountry',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'powder.com',
  },
  {
    id: 'ski-mag',
    url: 'https://www.skimag.com/feed/',
    name: 'Ski',
    description: 'Ski gear reviews, travel, and technique',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'skimag.com',
  },
  {
    id: 'adventure-journal',
    url: 'https://www.adventure-journal.com/feed/',
    name: 'Adventure Journal',
    description: 'Outdoor adventure stories and culture',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'adventure-journal.com',
  },
  {
    id: 'gear-junkie',
    url: 'https://gearjunkie.com/feed',
    name: 'GearJunkie',
    description: 'Outdoor gear reviews and adventure news',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'gearjunkie.com',
  },
  {
    id: 'outside-gear',
    url: 'https://www.outsideonline.com/outdoor-gear/feed/',
    name: 'Outside Gear',
    description: 'Outdoor gear reviews and buying guides',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'outsideonline.com',
  },
  {
    id: 'field-and-stream',
    url: 'https://www.fieldandstream.com/feed/',
    name: 'Field & Stream',
    description: 'Hunting, fishing, and outdoor skills',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'fieldandstream.com',
  },
  {
    id: 'outdoor-life',
    url: 'https://www.outdoorlife.com/feed/',
    name: 'Outdoor Life',
    description: 'Hunting, fishing, survival, and gear',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'outdoorlife.com',
  },
  {
    id: 'section-hiker',
    url: 'https://sectionhiker.com/feed/',
    name: 'Section Hiker',
    description: 'Backpacking trips, gear, and trail guides',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'sectionhiker.com',
  },
  {
    id: 'the-inertia',
    url: 'https://www.theinertia.com/feed/',
    name: 'The Inertia',
    description: 'Surf, snow, and outdoor action sports',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'theinertia.com',
  },
  {
    id: 'surfer',
    url: 'https://www.surfer.com/feed/',
    name: 'Surfer',
    description: 'Surf culture, travel, and wave reports',
    primaryTopic: 'sports',
    topics: ['sports', 'culture'],
    logoDomain: 'surfer.com',
  },
  {
    id: 'national-geographic',
    url: 'https://www.nationalgeographic.com/pages/topic/latest-stories/feed',
    name: 'National Geographic',
    description: 'Nature, exploration, science, and photography',
    primaryTopic: 'culture',
    topics: ['culture', 'world', 'science'],
    logoDomain: 'nationalgeographic.com',
  },
  {
    id: 'mens-health',
    url: 'https://www.menshealth.com/rss/all.xml/',
    name: "Men's Health",
    description: 'Fitness, training, nutrition, and wellness',
    primaryTopic: 'health',
    topics: ['health', 'sports'],
    sportTags: ['fitness'],
    logoDomain: 'menshealth.com',
  },
  {
    id: 'womens-health-mag',
    url: 'https://www.womenshealthmag.com/rss/all.xml/',
    name: "Women's Health",
    description: "Fitness, workouts, and women's wellness",
    primaryTopic: 'health',
    topics: ['health', 'sports'],
    sportTags: ['fitness'],
    logoDomain: 'womenshealthmag.com',
  },

  // —— Art ——
  {
    id: 'hyperallergic',
    url: 'https://hyperallergic.com/feed/',
    name: 'Hyperallergic',
    description: 'Contemporary art news and criticism',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
  },
  {
    id: 'artsy',
    url: 'https://www.artsy.net/rss/news',
    name: 'Artsy',
    description: 'Art market and exhibition news',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
  },
  {
    id: 'bbc-arts',
    url: 'https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml',
    name: 'BBC Arts',
    description: 'Entertainment and arts coverage',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
    logoDomain: 'bbc.co.uk',
  },
  {
    id: 'colossal',
    url: 'https://www.thisiscolossal.com/feed/',
    name: 'Colossal',
    description: 'Contemporary art, sculpture, and visual culture',
    primaryTopic: 'art',
    topics: ['art', 'culture', 'design'],
  },
  {
    id: 'artnet-news',
    url: 'https://news.artnet.com/feed',
    name: 'Artnet News',
    description: 'Art market news, exhibitions, and artist profiles',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
    logoDomain: 'artnet.com',
  },
  {
    id: 'artnews',
    url: 'https://www.artnews.com/feed/',
    name: 'ARTnews',
    description: 'Art world news, reviews, and market coverage',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
    subscriptionPublisher: true,
  },
  {
    id: 'artforum',
    url: 'https://www.artforum.com/feed/',
    name: 'Artforum',
    description: 'Contemporary art criticism and exhibition reviews',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
    subscriptionPublisher: true,
  },
  {
    id: 'juxtapoz',
    url: 'https://www.juxtapoz.com/feed/',
    name: 'Juxtapoz',
    description: 'Street art, illustration, and underground contemporary art',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
  },
  {
    id: 'art-newspaper',
    url: 'https://www.theartnewspaper.com/rss.xml',
    name: 'The Art Newspaper',
    description: 'International art news, museums, and heritage',
    primaryTopic: 'art',
    topics: ['art', 'culture', 'world'],
  },
  {
    id: 'artin-america',
    url: 'https://www.artinamericamagazine.com/feed/',
    name: 'Art in America',
    description: 'Contemporary art criticism and studio visits',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
    subscriptionPublisher: true,
  },
  {
    id: 'guardian-art-design',
    url: 'https://www.theguardian.com/artanddesign/rss',
    name: 'The Guardian Art & Design',
    description: 'Visual art, architecture, and design features',
    primaryTopic: 'art',
    topics: ['art', 'culture', 'design'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'designboom-art',
    url: 'https://www.designboom.com/art/feed/',
    name: 'designboom Art',
    description: 'Installation, public art, and contemporary sculpture',
    primaryTopic: 'art',
    topics: ['art', 'design'],
    logoDomain: 'designboom.com',
  },
  {
    id: 'smithsonian-arts',
    url: 'https://www.smithsonianmag.com/rss/arts-culture/',
    name: 'Smithsonian Arts & Culture',
    description: 'Museums, artists, and cultural history',
    primaryTopic: 'art',
    topics: ['art', 'culture'],
    logoDomain: 'smithsonianmag.com',
  },

  // —— Video games ——
  {
    id: 'ign',
    url: 'https://feeds.ign.com/ign/all',
    name: 'IGN',
    description: 'Game news, reviews, and entertainment',
    primaryTopic: 'gaming',
    topics: ['gaming'],
    logoDomain: 'ign.com',
  },
  {
    id: 'kotaku',
    url: 'https://kotaku.com/rss',
    name: 'Kotaku',
    description: 'Video game culture, news, and opinion',
    primaryTopic: 'gaming',
    topics: ['gaming', 'culture'],
  },
  {
    id: 'polygon',
    url: 'https://www.polygon.com/rss/index.xml',
    name: 'Polygon',
    description: 'Games, entertainment, and guides',
    primaryTopic: 'gaming',
    topics: ['gaming', 'culture'],
  },
  {
    id: 'eurogamer',
    url: 'https://www.eurogamer.net/feed',
    name: 'Eurogamer',
    description: 'Game news, reviews, and features',
    primaryTopic: 'gaming',
    topics: ['gaming'],
  },
  {
    id: 'rock-paper-shotgun',
    url: 'https://www.rockpapershotgun.com/feed',
    name: 'Rock Paper Shotgun',
    description: 'PC gaming news, reviews, and analysis',
    primaryTopic: 'gaming',
    topics: ['gaming'],
    logoDomain: 'rockpapershotgun.com',
  },
  {
    id: 'pc-gamer',
    url: 'https://www.pcgamer.com/rss/',
    name: 'PC Gamer',
    description: 'PC games, hardware, and esports',
    primaryTopic: 'gaming',
    topics: ['gaming'],
    logoDomain: 'pcgamer.com',
  },
  {
    id: 'gamesradar',
    url: 'https://www.gamesradar.com/feeds.xml',
    name: 'GamesRadar+',
    description: 'Game news, reviews, and upcoming releases',
    primaryTopic: 'gaming',
    topics: ['gaming'],
  },
  {
    id: 'gamespot',
    url: 'https://www.gamespot.com/feeds/news/',
    name: 'GameSpot',
    description: 'Game news, reviews, and videos',
    primaryTopic: 'gaming',
    topics: ['gaming'],
  },
  {
    id: 'nintendolife',
    url: 'https://www.nintendolife.com/feeds/latest',
    name: 'Nintendo Life',
    description: 'Nintendo news, reviews, and community',
    primaryTopic: 'gaming',
    topics: ['gaming'],
  },
  {
    id: 'push-square',
    url: 'https://www.pushsquare.com/feeds/latest',
    name: 'Push Square',
    description: 'PlayStation news, reviews, and guides',
    primaryTopic: 'gaming',
    topics: ['gaming'],
    logoDomain: 'pushsquare.com',
  },
  {
    id: 'gamesbeat',
    url: 'https://gamesbeat.com/feed/',
    name: 'GamesBeat',
    description: 'Game industry news and business analysis',
    primaryTopic: 'gaming',
    topics: ['gaming', 'business'],
    logoDomain: 'gamesbeat.com',
  },

  // —— Gardening ——
  {
    id: 'gardenista',
    url: 'https://www.gardenista.com/feed/',
    name: 'Gardenista',
    description: 'Garden design and outdoor living',
    primaryTopic: 'gardening',
    topics: ['gardening', 'design'],
    /** Gardenista origin is slow; allow extra time before treating as failed. */
    fetchTimeoutMs: 35_000,
  },
  {
    id: 'fine-gardening',
    url: 'https://www.gardenersworld.com/feed/',
    name: "BBC Gardeners' World",
    description: 'Plants, techniques, and garden design (Fine Gardening feed is offline)',
    primaryTopic: 'gardening',
    topics: ['gardening', 'design'],
    logoDomain: 'gardenersworld.com',
  },
  {
    id: 'gardening-etc',
    url: 'https://www.gardeningetc.com/feeds/all',
    name: 'Gardeningetc',
    description: 'Garden ideas, planting plans, and outdoor living',
    primaryTopic: 'gardening',
    topics: ['gardening', 'design'],
    logoDomain: 'gardeningetc.com',
  },
  {
    id: 'horticulture-mag',
    url: 'https://www.hortmag.com/feed/',
    name: 'Horticulture',
    description: 'Plants, garden design, and growing techniques',
    primaryTopic: 'gardening',
    topics: ['gardening', 'design'],
    logoDomain: 'hortmag.com',
  },
  {
    id: 'english-garden',
    url: 'https://www.theenglishgarden.co.uk/feed/',
    name: 'The English Garden',
    description: 'British gardens, plants, and seasonal inspiration',
    primaryTopic: 'gardening',
    topics: ['gardening', 'design'],
    logoDomain: 'theenglishgarden.co.uk',
  },
  {
    id: 'guardian-gardens',
    url: 'https://www.theguardian.com/lifeandstyle/gardens/rss',
    name: 'The Guardian Gardens',
    description: 'Gardening advice, grow-your-own, and design ideas',
    primaryTopic: 'gardening',
    topics: ['gardening', 'design'],
    logoDomain: 'theguardian.com',
  },
  {
    id: 'gardening-know-how',
    url: 'https://www.gardeningknowhow.com/feed/',
    name: 'Gardening Know How',
    description: 'Practical tips for vegetables, flowers, and landscaping',
    primaryTopic: 'gardening',
    topics: ['gardening'],
    logoDomain: 'gardeningknowhow.com',
  },
  {
    id: 'house-and-garden-uk',
    url: 'https://www.houseandgarden.co.uk/feed/rss',
    name: 'House & Garden',
    description: 'Garden design, planting, and outdoor entertaining',
    primaryTopic: 'gardening',
    topics: ['gardening', 'design'],
    logoDomain: 'houseandgarden.co.uk',
  },
  {
    id: 'garden-rant',
    url: 'https://feeds.feedburner.com/GardenRant',
    name: 'Garden Rant',
    description: 'Opinionated takes on plants, design, and garden culture',
    primaryTopic: 'gardening',
    topics: ['gardening', 'culture'],
    logoDomain: 'gardenrant.com',
  },
  {
    id: 'garden-and-gun',
    url: 'https://www.gardenandgun.com/feed/',
    name: 'Garden & Gun',
    description: 'Southern gardens, native plants, and outdoor living',
    primaryTopic: 'gardening',
    topics: ['gardening', 'culture', 'design'],
    logoDomain: 'gardenandgun.com',
  },

  // —— Design ——
  {
    id: 'dezeen',
    url: 'https://www.dezeen.com/feed/',
    name: 'Dezeen',
    description: 'Architecture, interiors, and design',
    primaryTopic: 'design',
    topics: ['design', 'culture', 'art'],
  },
];
